### ISSUE TITLE
ruby version 1.8 is old

### ISSUE THREAD

**Issue by realoptimal** [textmate/python.tmbundle#48]
Please consider untethering the bundle code from such an old version of ruby.  On mac os x yosemite, ruby version is 2.0.0p481

**Comment by infininight** [comment]
Using 1.8 of ruby allows us to use the same bundle command for older operating systems without testing and debugging two separate commands. We will migrate to 2.0 as needed for individual command features or overall once TextMate is 10.9+ only.

**Comment by realoptimal** [comment]
I modified my install to use a TM_RUBY env variable; with -K flag for backward compatibility.  Functions I've tried seem to work without issue.

**Comment by infininight** [comment]
This is the correct method. The `TM_RUBY` variable will be used when running your own code for instance the ruby run command, but for bundle items it will continue to use ruby 1.8.
