### ISSUE TITLE
Python syntax highlighting breaks on function annotations

### ISSUE THREAD

**Issue by aeschli** [textmate/python.tmbundle#51]
![screen shot 2015-12-18 at 10 13 02 pm](https://cloud.githubusercontent.com/assets/1039369/11910960/91ec729e-a5d4-11e5-8e73-465e1b3db73e.png)

Specifically, it looks like function annotations in Python 3 mess it up. The first docstring should be highlighted like the second.

This is with VSCode. For tokenizing VSCode uses the tokenizer from
https://github.com/textmate/python.tmbundle/blob/master/Syntaxes/Python.tmLanguage

**Comment by nchammas** [comment]
Looking through the issues in this repo, this appears to be a dup of #43.

**Comment by infininight** [comment]
Now corrected, changes should be compatible with VSCode as best I am aware but untested.

**Comment by monkeyplays23** [comment]
still seeing this issue 4 years later. Did we ever get a fix.

**Comment by sp96296** [comment]
> still seeing this issue 4 years later. Did we ever get a fix.

if so, I would like to know how to fix it because I am clueless
