### ISSUE TITLE
Installed bundle has white background in Dracula theme under PHPStorm

### ISSUE THREAD

**Issue by colford** [textmate/python.tmbundle#52]
I'm using PHPStorm on Ubuntu with this tmbundle. I've got the Dracula theme turned on but this bundle makes the background while instead of using the theme colours? Is there anyway to change this?

**Comment by sorbits** [comment]
You will have to use the support channel for PHPStorm and/or the Dracula team, as your problem is unlikely related to TextMate or this bundle.

**Comment by kolesnikova-tavi** [comment]
I have the same problem (webstorm, any dark theme)

**Comment by ztanner** [comment]
If you run into this issue, make sure that in the Textmate Bundles section of Webstorm/PHPStorm, you set the Textmate Color Scheme to "Darcula" for whatever user theme you have active. Mine was set to Mac Classic which made everything white.

**Comment by MatthiasKuehneEllerhold** [comment]
@ztanner I've got the same problem and your work around doesnt work. Do you have any other tips to get it working? Having a white background in the darcula theme is really annoying...

**Comment by FrancescJR** [comment]
Same issue here, with some other weird things, for example in my list of "File Types" (under settings editor) can't find any "textmate bundle" or "Files supported via TextMateb bundles", but if I try to add the reg exp "vagrantfile" to any other file type, it will complain that this one is reserved for "Files supported via TextMate bundles". I tried uninstalling and reindexing several times but I can just make it to the white background highlighted syntax file display

**Comment by ArminVieweg** [comment]
![2018-02-21_0849](https://user-images.githubusercontent.com/1275298/36468567-23b4291a-16e4-11e8-84d3-fcbb029de080.png)

I can confirm this issue, with latest PhpStorm 2017.3.4

Hope the screenshot helps you @FrancescJR to find the settings. But for me, it still does not work :/
But in an earlier version I got it somehow. So I've seen it working.

**Comment by ArminVieweg** [comment]
@FrancescJR I also was not able to find the option for Textmate in File Types. But a right click on my Vagrantfile offers me the "Mark as textmate" option.

**Comment by agarb7** [comment]
I found workaround. (I try on Ubuntu 17.10 with PhpStrom from snap package)

In file `~/.PhpStorm2017.3/config/options/textmate.xml`
To find `<entry key="_@user_Darcula" value="Darcula" />` similar string (with `_@user`). Replace for preferred theme (Darcula in my case). It's work for me.

**Comment by ArminVieweg** [comment]
Thanks dude! That works for me! And I also remember that this IDE Color Scheme list in PhpStorm contained the `_@user_Darcula` entry. So it's a bug in UI of PhpStorm.

**Comment by FrancescJR** [comment]
Yes! it works also with ubuntu 16.04. So that string had "classic mac" instead of darcula...

**Comment by bestit-ewieser** [comment]
On Mac OSX the file is under ~/Library/Preferences/PhpStormYYYY.x/options/textmate.xml.

I had to replace `<entry key="_@user_Darcula" value="Classic Mac" />` with `<entry key="_@user_Darcula" value="Darcula" />`.

**Comment by bskiefer** [comment]
If you sync your settings with github, textmate.xml is located at `~/Library/Preferences/PhpStorm2018.1/settingsRepository/repository`

Whatever your current color scheme is, change:
`<entry key="{theme}" value="Mac Classic" />`
to
`<entry key="{theme}" value="{theme}" />`

**Comment by z0dd** [comment]
Folder for windows users:
Press Win+R and type in:
`%userprofile%\.PhpStorm2017.3\config\options`
