### ISSUE TITLE
and, or, ... keywords not highlighted

### ISSUE THREAD

**Issue by jhasse** [textmate/python.tmbundle#56]
In Visual Studio Code `and` and `or` aren't highlighted in Python. GitHub highlights them which makes it much more readable:

```python
if a or b and c:
    pass
```

**Comment by NiklasRosenstein** [comment]
Same with the `in` keyword. Bump

**Comment by sorbits** [comment]
Closing issue as this works in TextMate, so I don’t think there is any issue with the grammar.

**Comment by jhasse** [comment]
@sorbits Are `=`, `+` in a different color than `and`, `or`? Sorry that I can't test myself, because I don't have a Mac.

**Comment by sorbits** [comment]
The color depends on the theme: http://manual.macromates.com/en/themes

The elements do have different scopes: 
keyword.operator.assignment.python and keyword.operator.logical.python 
respectively.

**Comment by jhasse** [comment]
Am I right to assume that themes would then color `keyword.operator.logical`?

**Comment by infininight** [comment]
Correct, you could target them with separate colors. Just use two rules with `keyword.operator.assignment` and `keyword.operator.logical`.
