### ISSUE TITLE
Poor whitespace removal by "Cleanup Whitespace"

### ISSUE THREAD

**Issue by fonnesbeck** [textmate/python.tmbundle#60]
When I run "Cleanup Whitespace" the code is not properly formatted following PEP8 recommendations. In fact, it appears that whitespace gets added in some places unexpectedly. Here is a GitHub diff of a file before and after using TextMate to clean it up:

![](http://d.pr/i/ZBRQrM+)

As you can see, trailing whitespace has been added to empty lines.

Using TM 2.0-rc.4.

**Comment by fonnesbeck** [comment]
Looks like this works when I use the "Remove trailing spaces in document" function in the text bundle. I had assumed the cleanup function included trailing white space.

**Comment by sorbits** [comment]
The _Cleanup Whitespace_ in the Python bundle will insert whitespace which appears to be a workaround for how foldings were done in Python for TextMate 1.x: f79456a48a4b9bf01951ed74a485e0a19442ad56

But the _Remove Trailing Spaces_ in the Text bundle will **not** insert whitespace, and should do what you want.

@infininight I suggest we remove the Cleanup Whitespace command to avoid confusion.
